"""Fix Company and Announcement models and relationships

Revision ID: 0e684cc2e606
Revises: 1ff3cf411698
Create Date: 2025-07-03 09:16:39.973288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0e684cc2e606'
down_revision = '1ff3cf411698'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scraped_announcements_id', table_name='scraped_announcements')
    op.drop_table('scraped_announcements')
    op.add_column('announcements', sa.Column('publication_date', sa.Date(), nullable=True))
    op.add_column('announcements', sa.Column('issue_number', sa.Integer(), nullable=True))
    op.add_column('announcements', sa.Column('page_number', sa.Integer(), nullable=True))
    op.add_column('announcements', sa.Column('announcement_type', sa.String(length=255), nullable=True))
    op.add_column('announcements', sa.Column('pdf_url', sa.String(length=1024), nullable=True))
    op.add_column('announcements', sa.Column('company_id', sa.UUID(), nullable=False))
    op.drop_index('ix_announcements_announcement_date', table_name='announcements')
    op.drop_index('ix_announcements_pdf_saved_to_supabase', table_name='announcements')
    op.create_index(op.f('ix_announcements_publication_date'), 'announcements', ['publication_date'], unique=False)
    op.create_foreign_key(None, 'announcements', 'companies', ['company_id'], ['id'])
    op.drop_column('announcements', 'supabase_path')
    op.drop_column('announcements', 'announcement_date')
    op.drop_column('announcements', 'pdf_link')
    op.drop_column('announcements', 'subject')
    op.drop_column('announcements', 'pdf_saved_to_supabase')
    op.add_column('companies', sa.Column('unvan', sa.String(length=500), nullable=True))
    op.add_column('companies', sa.Column('sicil_no', sa.String(length=50), nullable=True))
    op.alter_column('companies', 'establishment_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_company_title_trgm', table_name='companies', postgresql_using='gin')
    op.drop_index('ix_companies_tax_number', table_name='companies')
    op.drop_index('ix_companies_title', table_name='companies')
    op.drop_index('ix_companies_trade_registry_number', table_name='companies')
    op.create_index(op.f('ix_companies_sicil_no'), 'companies', ['sicil_no'], unique=True)
    op.create_index(op.f('ix_companies_unvan'), 'companies', ['unvan'], unique=False)
    op.drop_column('companies', 'postal_code')
    op.drop_column('companies', 'trade_name')
    op.drop_column('companies', 'tax_number')
    op.drop_column('companies', 'trade_registry_number')
    op.drop_column('companies', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('title', sa.VARCHAR(length=500), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('companies', sa.Column('trade_registry_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('tax_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('trade_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_companies_unvan'), table_name='companies')
    op.drop_index(op.f('ix_companies_sicil_no'), table_name='companies')
    op.create_index('ix_companies_trade_registry_number', 'companies', ['trade_registry_number'], unique=False)
    op.create_index('ix_companies_title', 'companies', ['title'], unique=False)
    op.create_index('ix_companies_tax_number', 'companies', ['tax_number'], unique=False)
    op.create_index('idx_company_title_trgm', 'companies', ['title'], unique=False, postgresql_using='gin')
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'establishment_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('companies', 'sicil_no')
    op.drop_column('companies', 'unvan')
    op.add_column('announcements', sa.Column('pdf_saved_to_supabase', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('announcements', sa.Column('subject', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('announcements', sa.Column('pdf_link', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('announcements', sa.Column('announcement_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('announcements', sa.Column('supabase_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'announcements', type_='foreignkey')
    op.drop_index(op.f('ix_announcements_publication_date'), table_name='announcements')
    op.create_index('ix_announcements_pdf_saved_to_supabase', 'announcements', ['pdf_saved_to_supabase'], unique=False)
    op.create_index('ix_announcements_announcement_date', 'announcements', ['announcement_date'], unique=False)
    op.drop_column('announcements', 'company_id')
    op.drop_column('announcements', 'pdf_url')
    op.drop_column('announcements', 'announcement_type')
    op.drop_column('announcements', 'page_number')
    op.drop_column('announcements', 'issue_number')
    op.drop_column('announcements', 'publication_date')
    op.create_table('scraped_announcements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('trade_registry_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('trade_registry_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('publication_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('issue_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('announcement_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pdf_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('scraped_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='scraped_announcements_company_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='scraped_announcements_pkey')
    )
    op.create_index('ix_scraped_announcements_id', 'scraped_announcements', ['id'], unique=False)
    # ### end Alembic commands ###
