"""Add updated_at to company_errors

Revision ID: 796d97fa7493
Revises: 32f1d763c12d
Create Date: 2025-12-05 22:00:19.068154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '796d97fa7493'
down_revision = '32f1d763c12d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_errors', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False), schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_errors', 'updated_at', schema='app')
    # ### end Alembic commands ###
