"""Add koordinat column to companies table

Revision ID: 84aead2bc192
Revises: c78e9c7e2a6e
Create Date: 2025-07-01 22:59:46.112723

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '84aead2bc192'
down_revision = 'c78e9c7e2a6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS postgis;')
    op.add_column('companies', sa.Column('koordinat', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.execute('DROP INDEX IF EXISTS idx_companies_koordinat;')
    op.create_index('idx_companies_koordinat', 'companies', ['koordinat'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_companies_koordinat', table_name='companies', postgresql_using='gist')
    op.drop_column('companies', 'koordinat')
    op.execute('DROP EXTENSION IF EXISTS postgis;')
    # ### end Alembic commands ###
