"""Add nace_code to Company model

Revision ID: 8cf22b64329c
Revises: 84aead2bc192
Create Date: 2025-07-03 08:23:13.958629

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8cf22b64329c'
down_revision = '84aead2bc192'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('nace_code', sa.String(length=255), nullable=True))
    # Add pdf_name and pdf_path columns as VARCHAR to match model
    op.add_column('companies', sa.Column('pdf_name', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('pdf_path', sa.String(), nullable=True))
    op.create_index(op.f('ix_companies_koordinat'), 'companies', ['koordinat'], unique=False)
    op.drop_column('companies', 'geocode_attempted_at')
    op.add_column('scraped_announcements', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('scraped_announcements', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('scraped_announcements', 'trade_registry_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('scraped_announcements', 'trade_registry_number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('scraped_announcements', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('scraped_announcements', 'announcement_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('scraped_announcements', 'pdf_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('scraped_announcements', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_scraped_announcements_id'), 'scraped_announcements', ['id'], unique=False)
    op.drop_constraint('scraped_announcements_company_id_fkey', 'scraped_announcements', type_='foreignkey')
    op.create_foreign_key(None, 'scraped_announcements', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scraped_announcements', type_='foreignkey')
    op.create_foreign_key('scraped_announcements_company_id_fkey', 'scraped_announcements', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_scraped_announcements_id'), table_name='scraped_announcements')
    op.alter_column('scraped_announcements', 'scraped_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scraped_announcements', 'pdf_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('scraped_announcements', 'announcement_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('scraped_announcements', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('scraped_announcements', 'trade_registry_number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('scraped_announcements', 'trade_registry_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('scraped_announcements', 'updated_at')
    op.drop_column('scraped_announcements', 'created_at')
    op.add_column('companies', sa.Column('geocode_attempted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_companies_koordinat'), table_name='companies')
    op.alter_column('companies', 'pdf_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('companies', 'pdf_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('companies', 'nace_code')
    # ### end Alembic commands ###
