"""add_contact_messages_table

Revision ID: bf1009336cbe
Revises: 796d97fa7493
Create Date: 2025-12-06 00:27:10.371061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf1009336cbe'
down_revision = '796d97fa7493'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_contact_messages_email'), 'contact_messages', ['email'], unique=False, schema='app')
    op.create_index(op.f('ix_app_contact_messages_id'), 'contact_messages', ['id'], unique=False, schema='app')
    op.drop_index('idx_announcements_company_id', table_name='announcements', schema='app')
    op.create_index(op.f('ix_app_announcements_id'), 'announcements', ['id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_announcements_publication_date'), 'announcements', ['publication_date'], unique=False, schema='app')
    op.create_index(op.f('ix_app_announcements_title'), 'announcements', ['title'], unique=False, schema='app')
    op.create_index(op.f('ix_app_announcements_trade_registry_name'), 'announcements', ['trade_registry_name'], unique=False, schema='app')
    op.create_index(op.f('ix_app_announcements_trade_registry_number'), 'announcements', ['trade_registry_number'], unique=False, schema='app')
    op.drop_column('announcements', 'ocr_processed_at', schema='app')
    op.drop_column('announcements', 'ocr_status', schema='app')
    op.drop_column('announcements', 'title_unaccent', schema='app')
    op.drop_column('announcements', 'pdf_deleted', schema='app')
    op.create_index(op.f('ix_app_app_settings_key'), 'app_settings', ['key'], unique=False, schema='app')
    op.alter_column('app_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'),
               schema='app')
    op.alter_column('app_users', 'is_banned',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'),
               schema='app')
    op.alter_column('app_users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'MANAGER', 'USER', name='userrole', schema='app'),
               type_=sa.Enum('ADMIN', 'MANAGER', 'USER', name='userrole'),
               existing_nullable=False,
               schema='app')
    op.drop_constraint('app_users_email_key', 'app_users', schema='app', type_='unique')
    op.create_index(op.f('ix_app_app_users_email'), 'app_users', ['email'], unique=True, schema='app')
    op.create_index(op.f('ix_app_app_users_id'), 'app_users', ['id'], unique=False, schema='app')
    op.drop_constraint('companies_mersis_number_key', 'companies', schema='app', type_='unique')
    op.drop_index('idx_companies_mersis_number', table_name='companies', schema='app')
    op.drop_index('idx_companies_sicil_no', table_name='companies', schema='app')
    op.drop_index('idx_companies_sicil_office_code', table_name='companies', schema='app')
    op.drop_index('idx_companies_unvan_trgm', table_name='companies', schema='app', postgresql_using='gin')
    op.drop_index('idx_companies_unvan_unaccent_trgm', table_name='companies', schema='app', postgresql_using='gin')
    op.create_index(op.f('ix_app_companies_id'), 'companies', ['id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_companies_koordinat'), 'companies', ['koordinat'], unique=False, schema='app')
    op.create_index(op.f('ix_app_companies_mersis_number'), 'companies', ['mersis_number'], unique=True, schema='app')
    op.create_index(op.f('ix_app_companies_sicil_no'), 'companies', ['sicil_no'], unique=False, schema='app')
    op.create_index(op.f('ix_app_companies_sicil_office_code'), 'companies', ['sicil_office_code'], unique=False, schema='app')
    op.create_index(op.f('ix_app_companies_unvan'), 'companies', ['unvan'], unique=False, schema='app')
    op.drop_column('companies', 'address_unaccent', schema='app')
    op.drop_column('companies', 'sicil_no_unaccent', schema='app')
    op.drop_column('companies', 'unvan_unaccent', schema='app')
    op.alter_column('company_person_relations', 'relation_type',
               existing_type=postgresql.ENUM('SHAREHOLDER', 'MANAGER', 'BOARD_MEMBER', 'AUDITOR', 'OTHER', name='relationtype', schema='app'),
               type_=sa.Enum('BOARD_MEMBER', 'SHAREHOLDER', 'AUTHORIZED_SIGNATORY', 'AUDITOR', 'LIQUIDATOR', 'OTHER', name='relationtype'),
               existing_nullable=False,
               schema='app')
    op.create_index('idx_relation_company_person', 'company_person_relations', ['company_id', 'person_id', 'relation_type'], unique=False, schema='app')
    op.create_index('idx_relation_dates', 'company_person_relations', ['start_date', 'end_date'], unique=False, schema='app')
    op.create_index(op.f('ix_app_company_person_relations_end_date'), 'company_person_relations', ['end_date'], unique=False, schema='app')
    op.create_index(op.f('ix_app_company_person_relations_is_current'), 'company_person_relations', ['is_current'], unique=False, schema='app')
    op.create_index(op.f('ix_app_company_person_relations_relation_type'), 'company_person_relations', ['relation_type'], unique=False, schema='app')
    op.create_index(op.f('ix_app_company_person_relations_start_date'), 'company_person_relations', ['start_date'], unique=False, schema='app')
    op.drop_constraint('daily_usages_user_id_day_key', 'daily_usages', schema='app', type_='unique')
    op.create_index(op.f('ix_app_daily_usages_day'), 'daily_usages', ['day'], unique=False, schema='app')
    op.create_index(op.f('ix_app_daily_usages_user_id'), 'daily_usages', ['user_id'], unique=False, schema='app')
    op.create_unique_constraint('uq_daily_usage_user_day', 'daily_usages', ['user_id', 'day'], schema='app')
    op.alter_column('file_uploads', 'upload_type',
               existing_type=postgresql.ENUM('GAZETTE', 'COMPANY', 'PERSON', 'OTHER', name='fileuploadtype', schema='app'),
               type_=sa.Enum('GAZETTE_PDF', 'COMPANY_DATA', 'PERSON_DATA', 'OTHER', name='fileuploadtype'),
               existing_nullable=False,
               schema='app')
    op.alter_column('file_uploads', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='fileuploadstatus', schema='app'),
               type_=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='fileuploadstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'PENDING'::app.fileuploadstatus"),
               schema='app')
    op.create_index(op.f('ix_app_file_uploads_id'), 'file_uploads', ['id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_file_uploads_status'), 'file_uploads', ['status'], unique=False, schema='app')
    op.create_index(op.f('ix_app_file_uploads_uploaded_by_id'), 'file_uploads', ['uploaded_by_id'], unique=False, schema='app')
    op.drop_index('idx_gazette_entries_company_id', table_name='gazette_entries', schema='app')
    op.drop_index('idx_gazette_entries_gazette_id', table_name='gazette_entries', schema='app')
    op.create_index('idx_entry_type_date', 'gazette_entries', ['entry_type', 'entry_date'], unique=False, schema='app')
    op.create_index(op.f('ix_app_gazette_entries_company_id'), 'gazette_entries', ['company_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_gazette_entries_entry_date'), 'gazette_entries', ['entry_date'], unique=False, schema='app')
    op.create_index(op.f('ix_app_gazette_entries_gazette_id'), 'gazette_entries', ['gazette_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_gazette_entries_id'), 'gazette_entries', ['id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_gazette_entries_is_processed'), 'gazette_entries', ['is_processed'], unique=False, schema='app')
    op.drop_column('gazette_entries', 'processed_text_unaccent', schema='app')
    op.alter_column('gazettes', 'gazette_type',
               existing_type=postgresql.ENUM('TRADE_REGISTRY', 'OFFICIAL', 'OTHER', name='gazettetype', schema='app'),
               type_=sa.Enum('TRADE', 'ANNOUNCEMENT', 'OTHER', name='gazettetype'),
               existing_nullable=False,
               schema='app')
    op.create_index('idx_gazette_date_type', 'gazettes', ['gazette_date', 'gazette_type'], unique=False, schema='app')
    op.create_index(op.f('ix_app_gazettes_gazette_date'), 'gazettes', ['gazette_date'], unique=False, schema='app')
    op.create_index(op.f('ix_app_gazettes_gazette_number'), 'gazettes', ['gazette_number'], unique=False, schema='app')
    op.create_index(op.f('ix_app_gazettes_id'), 'gazettes', ['id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_gazettes_is_processed'), 'gazettes', ['is_processed'], unique=False, schema='app')
    op.alter_column('job_histories', 'job_type',
               existing_type=postgresql.ENUM('IMPORT', 'EXPORT', 'PROCESS', 'CLEANUP', 'OTHER', name='jobtype', schema='app'),
               type_=sa.Enum('FILE_UPLOAD', 'OCR_PROCESSING', 'DATA_IMPORT', 'DATA_EXPORT', 'REPORT_GENERATION', 'SYSTEM_MAINTENANCE', 'OTHER', name='jobtype'),
               existing_nullable=False,
               schema='app')
    op.alter_column('job_histories', 'status',
               existing_type=postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus', schema='app'),
               type_=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'PENDING'::app.jobstatus"),
               schema='app')
    op.create_index('idx_job_dates', 'job_histories', ['started_at', 'completed_at'], unique=False, schema='app')
    op.create_index('idx_job_type_status', 'job_histories', ['job_type', 'status'], unique=False, schema='app')
    op.create_index(op.f('ix_app_job_histories_file_upload_id'), 'job_histories', ['file_upload_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_job_histories_id'), 'job_histories', ['id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_job_histories_job_name'), 'job_histories', ['job_name'], unique=False, schema='app')
    op.create_index(op.f('ix_app_job_histories_job_type'), 'job_histories', ['job_type'], unique=False, schema='app')
    op.create_index(op.f('ix_app_job_histories_started_at'), 'job_histories', ['started_at'], unique=False, schema='app')
    op.create_index(op.f('ix_app_job_histories_status'), 'job_histories', ['status'], unique=False, schema='app')
    op.create_index(op.f('ix_app_job_histories_user_id'), 'job_histories', ['user_id'], unique=False, schema='app')
    op.alter_column('ocr_results', 'company_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='app')
    op.alter_column('ocr_results', 'publication_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               schema='app')
    op.alter_column('ocr_results', 'addresses',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               schema='app')
    op.alter_column('ocr_results', 'old_addresses',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               schema='app')
    op.alter_column('ocr_results', 'persons',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               schema='app')
    op.alter_column('ocr_results', 'masked_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               schema='app')
    op.alter_column('ocr_results', 'hususlar',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               schema='app')
    op.alter_column('ocr_results', 'ilan_sira_no',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               schema='app')
    op.alter_column('ocr_results', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text("'pending'::text"),
               schema='app')
    op.drop_index('idx_ocr_results_announcement_id', table_name='ocr_results', schema='app')
    op.drop_index('idx_ocr_results_company_id', table_name='ocr_results', schema='app')
    op.drop_constraint('uq_ocr_results_announcement_item', 'ocr_results', schema='app', type_='unique')
    op.create_index(op.f('ix_app_ocr_results_announcement_id'), 'ocr_results', ['announcement_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_ocr_results_company_id'), 'ocr_results', ['company_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_ocr_results_id'), 'ocr_results', ['id'], unique=False, schema='app')
    op.drop_constraint('ocr_results_company_id_fkey', 'ocr_results', schema='app', type_='foreignkey')
    op.create_foreign_key(None, 'ocr_results', 'companies', ['company_id'], ['id'], source_schema='app', referent_schema='app')
    op.drop_index('idx_persons_masked_id', table_name='persons', schema='app')
    op.create_index('idx_person_name_trgm', 'persons', ['full_name'], unique=False, schema='app', postgresql_using='gin', postgresql_ops={'full_name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_app_persons_email'), 'persons', ['email'], unique=False, schema='app')
    op.create_index(op.f('ix_app_persons_first_name'), 'persons', ['first_name'], unique=False, schema='app')
    op.create_index(op.f('ix_app_persons_full_name'), 'persons', ['full_name'], unique=False, schema='app')
    op.create_index(op.f('ix_app_persons_id'), 'persons', ['id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_persons_last_name'), 'persons', ['last_name'], unique=False, schema='app')
    op.create_index(op.f('ix_app_persons_masked_id'), 'persons', ['masked_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_persons_nationality_id'), 'persons', ['nationality_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_persons_passport_number'), 'persons', ['passport_number'], unique=False, schema='app')
    op.drop_column('persons', 'first_name_unaccent', schema='app')
    op.drop_column('persons', 'last_name_unaccent', schema='app')
    op.drop_column('persons', 'email_unaccent', schema='app')
    op.drop_column('persons', 'full_name_unaccent', schema='app')
    op.drop_constraint('user_invites_token_key', 'user_invites', schema='app', type_='unique')
    op.create_index(op.f('ix_app_user_invites_invited_email'), 'user_invites', ['invited_email'], unique=False, schema='app')
    op.create_index(op.f('ix_app_user_invites_invited_month_key'), 'user_invites', ['invited_month_key'], unique=False, schema='app')
    op.create_index(op.f('ix_app_user_invites_inviter_user_id'), 'user_invites', ['inviter_user_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_user_invites_token'), 'user_invites', ['token'], unique=True, schema='app')
    op.drop_column('user_invites', 'revoked_at', schema='app')
    op.drop_column('user_invites', 'expires_at', schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_invites', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='app')
    op.add_column('user_invites', sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='app')
    op.drop_index(op.f('ix_app_user_invites_token'), table_name='user_invites', schema='app')
    op.drop_index(op.f('ix_app_user_invites_inviter_user_id'), table_name='user_invites', schema='app')
    op.drop_index(op.f('ix_app_user_invites_invited_month_key'), table_name='user_invites', schema='app')
    op.drop_index(op.f('ix_app_user_invites_invited_email'), table_name='user_invites', schema='app')
    op.create_unique_constraint('user_invites_token_key', 'user_invites', ['token'], schema='app')
    op.add_column('persons', sa.Column('full_name_unaccent', sa.TEXT(), sa.Computed('tr_normalize((full_name)::text)', persisted=True), autoincrement=False, nullable=True), schema='app')
    op.add_column('persons', sa.Column('email_unaccent', sa.TEXT(), sa.Computed('tr_normalize((email)::text)', persisted=True), autoincrement=False, nullable=True), schema='app')
    op.add_column('persons', sa.Column('last_name_unaccent', sa.TEXT(), sa.Computed('tr_normalize((last_name)::text)', persisted=True), autoincrement=False, nullable=True), schema='app')
    op.add_column('persons', sa.Column('first_name_unaccent', sa.TEXT(), sa.Computed('tr_normalize((first_name)::text)', persisted=True), autoincrement=False, nullable=True), schema='app')
    op.drop_index(op.f('ix_app_persons_passport_number'), table_name='persons', schema='app')
    op.drop_index(op.f('ix_app_persons_nationality_id'), table_name='persons', schema='app')
    op.drop_index(op.f('ix_app_persons_masked_id'), table_name='persons', schema='app')
    op.drop_index(op.f('ix_app_persons_last_name'), table_name='persons', schema='app')
    op.drop_index(op.f('ix_app_persons_id'), table_name='persons', schema='app')
    op.drop_index(op.f('ix_app_persons_full_name'), table_name='persons', schema='app')
    op.drop_index(op.f('ix_app_persons_first_name'), table_name='persons', schema='app')
    op.drop_index(op.f('ix_app_persons_email'), table_name='persons', schema='app')
    op.drop_index('idx_person_name_trgm', table_name='persons', schema='app', postgresql_using='gin', postgresql_ops={'full_name': 'gin_trgm_ops'})
    op.create_index('idx_persons_masked_id', 'persons', ['masked_id'], unique=False, schema='app')
    op.drop_constraint(None, 'ocr_results', schema='app', type_='foreignkey')
    op.create_foreign_key('ocr_results_company_id_fkey', 'ocr_results', 'companies', ['company_id'], ['id'], source_schema='app', referent_schema='app', ondelete='SET NULL')
    op.drop_index(op.f('ix_app_ocr_results_id'), table_name='ocr_results', schema='app')
    op.drop_index(op.f('ix_app_ocr_results_company_id'), table_name='ocr_results', schema='app')
    op.drop_index(op.f('ix_app_ocr_results_announcement_id'), table_name='ocr_results', schema='app')
    op.create_unique_constraint('uq_ocr_results_announcement_item', 'ocr_results', ['announcement_id', 'item_index'], schema='app')
    op.create_index('idx_ocr_results_company_id', 'ocr_results', ['company_id'], unique=False, schema='app')
    op.create_index('idx_ocr_results_announcement_id', 'ocr_results', ['announcement_id'], unique=False, schema='app')
    op.alter_column('ocr_results', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'pending'::text"),
               schema='app')
    op.alter_column('ocr_results', 'ilan_sira_no',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='app')
    op.alter_column('ocr_results', 'hususlar',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='app')
    op.alter_column('ocr_results', 'masked_ids',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='app')
    op.alter_column('ocr_results', 'persons',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='app')
    op.alter_column('ocr_results', 'old_addresses',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='app')
    op.alter_column('ocr_results', 'addresses',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='app')
    op.alter_column('ocr_results', 'publication_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True,
               schema='app')
    op.alter_column('ocr_results', 'company_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='app')
    op.drop_index(op.f('ix_app_job_histories_user_id'), table_name='job_histories', schema='app')
    op.drop_index(op.f('ix_app_job_histories_status'), table_name='job_histories', schema='app')
    op.drop_index(op.f('ix_app_job_histories_started_at'), table_name='job_histories', schema='app')
    op.drop_index(op.f('ix_app_job_histories_job_type'), table_name='job_histories', schema='app')
    op.drop_index(op.f('ix_app_job_histories_job_name'), table_name='job_histories', schema='app')
    op.drop_index(op.f('ix_app_job_histories_id'), table_name='job_histories', schema='app')
    op.drop_index(op.f('ix_app_job_histories_file_upload_id'), table_name='job_histories', schema='app')
    op.drop_index('idx_job_type_status', table_name='job_histories', schema='app')
    op.drop_index('idx_job_dates', table_name='job_histories', schema='app')
    op.alter_column('job_histories', 'status',
               existing_type=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'),
               type_=postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus', schema='app'),
               existing_nullable=True,
               existing_server_default=sa.text("'PENDING'::app.jobstatus"),
               schema='app')
    op.alter_column('job_histories', 'job_type',
               existing_type=sa.Enum('FILE_UPLOAD', 'OCR_PROCESSING', 'DATA_IMPORT', 'DATA_EXPORT', 'REPORT_GENERATION', 'SYSTEM_MAINTENANCE', 'OTHER', name='jobtype'),
               type_=postgresql.ENUM('IMPORT', 'EXPORT', 'PROCESS', 'CLEANUP', 'OTHER', name='jobtype', schema='app'),
               existing_nullable=False,
               schema='app')
    op.drop_index(op.f('ix_app_gazettes_is_processed'), table_name='gazettes', schema='app')
    op.drop_index(op.f('ix_app_gazettes_id'), table_name='gazettes', schema='app')
    op.drop_index(op.f('ix_app_gazettes_gazette_number'), table_name='gazettes', schema='app')
    op.drop_index(op.f('ix_app_gazettes_gazette_date'), table_name='gazettes', schema='app')
    op.drop_index('idx_gazette_date_type', table_name='gazettes', schema='app')
    op.alter_column('gazettes', 'gazette_type',
               existing_type=sa.Enum('TRADE', 'ANNOUNCEMENT', 'OTHER', name='gazettetype'),
               type_=postgresql.ENUM('TRADE_REGISTRY', 'OFFICIAL', 'OTHER', name='gazettetype', schema='app'),
               existing_nullable=False,
               schema='app')
    op.add_column('gazette_entries', sa.Column('processed_text_unaccent', sa.TEXT(), sa.Computed('tr_normalize(processed_text)', persisted=True), autoincrement=False, nullable=True), schema='app')
    op.drop_index(op.f('ix_app_gazette_entries_is_processed'), table_name='gazette_entries', schema='app')
    op.drop_index(op.f('ix_app_gazette_entries_id'), table_name='gazette_entries', schema='app')
    op.drop_index(op.f('ix_app_gazette_entries_gazette_id'), table_name='gazette_entries', schema='app')
    op.drop_index(op.f('ix_app_gazette_entries_entry_date'), table_name='gazette_entries', schema='app')
    op.drop_index(op.f('ix_app_gazette_entries_company_id'), table_name='gazette_entries', schema='app')
    op.drop_index('idx_entry_type_date', table_name='gazette_entries', schema='app')
    op.create_index('idx_gazette_entries_gazette_id', 'gazette_entries', ['gazette_id'], unique=False, schema='app')
    op.create_index('idx_gazette_entries_company_id', 'gazette_entries', ['company_id'], unique=False, schema='app')
    op.drop_index(op.f('ix_app_file_uploads_uploaded_by_id'), table_name='file_uploads', schema='app')
    op.drop_index(op.f('ix_app_file_uploads_status'), table_name='file_uploads', schema='app')
    op.drop_index(op.f('ix_app_file_uploads_id'), table_name='file_uploads', schema='app')
    op.alter_column('file_uploads', 'status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='fileuploadstatus'),
               type_=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='fileuploadstatus', schema='app'),
               existing_nullable=True,
               existing_server_default=sa.text("'PENDING'::app.fileuploadstatus"),
               schema='app')
    op.alter_column('file_uploads', 'upload_type',
               existing_type=sa.Enum('GAZETTE_PDF', 'COMPANY_DATA', 'PERSON_DATA', 'OTHER', name='fileuploadtype'),
               type_=postgresql.ENUM('GAZETTE', 'COMPANY', 'PERSON', 'OTHER', name='fileuploadtype', schema='app'),
               existing_nullable=False,
               schema='app')
    op.drop_constraint('uq_daily_usage_user_day', 'daily_usages', schema='app', type_='unique')
    op.drop_index(op.f('ix_app_daily_usages_user_id'), table_name='daily_usages', schema='app')
    op.drop_index(op.f('ix_app_daily_usages_day'), table_name='daily_usages', schema='app')
    op.create_unique_constraint('daily_usages_user_id_day_key', 'daily_usages', ['user_id', 'day'], schema='app')
    op.drop_index(op.f('ix_app_company_person_relations_start_date'), table_name='company_person_relations', schema='app')
    op.drop_index(op.f('ix_app_company_person_relations_relation_type'), table_name='company_person_relations', schema='app')
    op.drop_index(op.f('ix_app_company_person_relations_is_current'), table_name='company_person_relations', schema='app')
    op.drop_index(op.f('ix_app_company_person_relations_end_date'), table_name='company_person_relations', schema='app')
    op.drop_index('idx_relation_dates', table_name='company_person_relations', schema='app')
    op.drop_index('idx_relation_company_person', table_name='company_person_relations', schema='app')
    op.alter_column('company_person_relations', 'relation_type',
               existing_type=sa.Enum('BOARD_MEMBER', 'SHAREHOLDER', 'AUTHORIZED_SIGNATORY', 'AUDITOR', 'LIQUIDATOR', 'OTHER', name='relationtype'),
               type_=postgresql.ENUM('SHAREHOLDER', 'MANAGER', 'BOARD_MEMBER', 'AUDITOR', 'OTHER', name='relationtype', schema='app'),
               existing_nullable=False,
               schema='app')
    op.add_column('companies', sa.Column('unvan_unaccent', sa.TEXT(), sa.Computed('tr_normalize((unvan)::text)', persisted=True), autoincrement=False, nullable=True), schema='app')
    op.add_column('companies', sa.Column('sicil_no_unaccent', sa.TEXT(), sa.Computed('tr_normalize((sicil_no)::text)', persisted=True), autoincrement=False, nullable=True), schema='app')
    op.add_column('companies', sa.Column('address_unaccent', sa.TEXT(), sa.Computed('tr_normalize(address)', persisted=True), autoincrement=False, nullable=True), schema='app')
    op.drop_index(op.f('ix_app_companies_unvan'), table_name='companies', schema='app')
    op.drop_index(op.f('ix_app_companies_sicil_office_code'), table_name='companies', schema='app')
    op.drop_index(op.f('ix_app_companies_sicil_no'), table_name='companies', schema='app')
    op.drop_index(op.f('ix_app_companies_mersis_number'), table_name='companies', schema='app')
    op.drop_index(op.f('ix_app_companies_koordinat'), table_name='companies', schema='app')
    op.drop_index(op.f('ix_app_companies_id'), table_name='companies', schema='app')
    op.create_index('idx_companies_unvan_unaccent_trgm', 'companies', ['unvan_unaccent'], unique=False, schema='app', postgresql_using='gin')
    op.create_index('idx_companies_unvan_trgm', 'companies', ['unvan'], unique=False, schema='app', postgresql_using='gin')
    op.create_index('idx_companies_sicil_office_code', 'companies', ['sicil_office_code'], unique=False, schema='app')
    op.create_index('idx_companies_sicil_no', 'companies', ['sicil_no'], unique=False, schema='app')
    op.create_index('idx_companies_mersis_number', 'companies', ['mersis_number'], unique=False, schema='app')
    op.create_unique_constraint('companies_mersis_number_key', 'companies', ['mersis_number'], schema='app')
    op.drop_index(op.f('ix_app_app_users_id'), table_name='app_users', schema='app')
    op.drop_index(op.f('ix_app_app_users_email'), table_name='app_users', schema='app')
    op.create_unique_constraint('app_users_email_key', 'app_users', ['email'], schema='app')
    op.alter_column('app_users', 'role',
               existing_type=sa.Enum('ADMIN', 'MANAGER', 'USER', name='userrole'),
               type_=postgresql.ENUM('ADMIN', 'MANAGER', 'USER', name='userrole', schema='app'),
               existing_nullable=False,
               schema='app')
    op.alter_column('app_users', 'is_banned',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'),
               schema='app')
    op.alter_column('app_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'),
               schema='app')
    op.drop_index(op.f('ix_app_app_settings_key'), table_name='app_settings', schema='app')
    op.add_column('announcements', sa.Column('pdf_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True), schema='app')
    op.add_column('announcements', sa.Column('title_unaccent', sa.TEXT(), sa.Computed('tr_normalize((title)::text)', persisted=True), autoincrement=False, nullable=True), schema='app')
    op.add_column('announcements', sa.Column('ocr_status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=True), schema='app')
    op.add_column('announcements', sa.Column('ocr_processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='app')
    op.drop_index(op.f('ix_app_announcements_trade_registry_number'), table_name='announcements', schema='app')
    op.drop_index(op.f('ix_app_announcements_trade_registry_name'), table_name='announcements', schema='app')
    op.drop_index(op.f('ix_app_announcements_title'), table_name='announcements', schema='app')
    op.drop_index(op.f('ix_app_announcements_publication_date'), table_name='announcements', schema='app')
    op.drop_index(op.f('ix_app_announcements_id'), table_name='announcements', schema='app')
    op.create_index('idx_announcements_company_id', 'announcements', ['company_id'], unique=False, schema='app')
    op.drop_index(op.f('ix_app_contact_messages_id'), table_name='contact_messages', schema='app')
    op.drop_index(op.f('ix_app_contact_messages_email'), table_name='contact_messages', schema='app')
    op.drop_table('contact_messages', schema='app')
    # ### end Alembic commands ###
