"""Remove outdated company_scrape model and table

Revision ID: c5ad8926b2d5
Revises: 0e684cc2e606
Create Date: 2025-07-03 11:21:17.585285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5ad8926b2d5'
down_revision = '0e684cc2e606'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_company_scrapes_id', table_name='company_scrapes')
    op.drop_index('ix_company_scrapes_sicil_no', table_name='company_scrapes')
    op.drop_table('company_scrapes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_scrapes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sicil_no', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('firma_unvani', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_scraped', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_scraped_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='company_scrapes_pkey')
    )
    op.create_index('ix_company_scrapes_sicil_no', 'company_scrapes', ['sicil_no'], unique=False)
    op.create_index('ix_company_scrapes_id', 'company_scrapes', ['id'], unique=False)
    # ### end Alembic commands ###
