import geoalchemy2
"""Initial schema setup

Revision ID: c627952a2863
Revises: 
Create Date: 2026-05-14 20:31:42.928706

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c627952a2863'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key'),
    schema='app'
    )
    op.create_index(op.f('ix_app_app_settings_key'), 'app_settings', ['key'], unique=False, schema='app')
    op.create_table('app_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'USER', name='userrole'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_session_iat', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_app_users_email'), 'app_users', ['email'], unique=True, schema='app')
    op.create_index(op.f('ix_app_app_users_id'), 'app_users', ['id'], unique=False, schema='app')
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unvan', sa.String(length=500), nullable=True),
    sa.Column('unvan_unaccent', sa.Text(), sa.Computed('tr_normalize(unvan)', ), nullable=True),
    sa.Column('mersis_number', sa.String(length=50), nullable=True),
    sa.Column('sicil_no', sa.String(length=50), nullable=True),
    sa.Column('sicil_mudurluk', sa.String(length=255), nullable=True),
    sa.Column('sicil_office_code', sa.String(length=64), nullable=True),
    sa.Column('nace_code', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('koordinat', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('establishment_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('pdf_name', sa.String(), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sicil_no', 'sicil_office_code', name='ux_companies_sicil_no_office'),
    schema='app'
    )
    op.create_index(op.f('ix_app_companies_id'), 'companies', ['id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_companies_mersis_number'), 'companies', ['mersis_number'], unique=True, schema='app')
    op.create_index(op.f('ix_app_companies_sicil_no'), 'companies', ['sicil_no'], unique=False, schema='app')
    op.create_index(op.f('ix_app_companies_sicil_office_code'), 'companies', ['sicil_office_code'], unique=False, schema='app')
    op.create_index(op.f('ix_app_companies_unvan'), 'companies', ['unvan'], unique=False, schema='app')
    op.create_index(op.f('ix_app_companies_unvan_unaccent'), 'companies', ['unvan_unaccent'], unique=False, schema='app')
    op.create_table('contact_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_contact_messages_email'), 'contact_messages', ['email'], unique=False, schema='app')
    op.create_index(op.f('ix_app_contact_messages_id'), 'contact_messages', ['id'], unique=False, schema='app')
    op.create_table('daily_usages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', name='uq_daily_usage_user_day'),
    schema='app'
    )
    op.create_index(op.f('ix_app_daily_usages_day'), 'daily_usages', ['day'], unique=False, schema='app')
    op.create_index(op.f('ix_app_daily_usages_user_id'), 'daily_usages', ['user_id'], unique=False, schema='app')
    op.create_table('gazettes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gazette_number', sa.String(length=100), nullable=True),
    sa.Column('gazette_date', sa.DateTime(), nullable=False),
    sa.Column('gazette_type', sa.Enum('TRADE', 'ANNOUNCEMENT', 'OTHER', name='gazettetype'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('idx_gazette_date_type', 'gazettes', ['gazette_date', 'gazette_type'], unique=False, schema='app')
    op.create_index(op.f('ix_app_gazettes_gazette_date'), 'gazettes', ['gazette_date'], unique=False, schema='app')
    op.create_index(op.f('ix_app_gazettes_gazette_number'), 'gazettes', ['gazette_number'], unique=False, schema='app')
    op.create_index(op.f('ix_app_gazettes_id'), 'gazettes', ['id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_gazettes_is_processed'), 'gazettes', ['is_processed'], unique=False, schema='app')
    op.create_table('geocoding_cache',
    sa.Column('address_hash', sa.String(length=64), nullable=False),
    sa.Column('address_text', sa.String(length=1000), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('address_hash'),
    schema='app'
    )
    op.create_index(op.f('ix_app_geocoding_cache_address_hash'), 'geocoding_cache', ['address_hash'], unique=False, schema='app')
    op.create_table('incoming_emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_address', sa.String(length=255), nullable=False),
    sa.Column('to_address', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('cloudflare_message_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_incoming_emails_cloudflare_message_id'), 'incoming_emails', ['cloudflare_message_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_incoming_emails_from_address'), 'incoming_emails', ['from_address'], unique=False, schema='app')
    op.create_index(op.f('ix_app_incoming_emails_id'), 'incoming_emails', ['id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_incoming_emails_is_read'), 'incoming_emails', ['is_read'], unique=False, schema='app')
    op.create_index(op.f('ix_app_incoming_emails_received_at'), 'incoming_emails', ['received_at'], unique=False, schema='app')
    op.create_index(op.f('ix_app_incoming_emails_to_address'), 'incoming_emails', ['to_address'], unique=False, schema='app')
    op.create_table('persons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=300), nullable=True),
    sa.Column('masked_id', sa.String(length=20), nullable=True),
    sa.Column('nationality_id', sa.String(length=20), nullable=True),
    sa.Column('passport_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('birth_place', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('idx_person_name_trgm', 'persons', ['full_name'], unique=False, schema='app', postgresql_using='gin', postgresql_ops={'full_name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_app_persons_email'), 'persons', ['email'], unique=False, schema='app')
    op.create_index(op.f('ix_app_persons_first_name'), 'persons', ['first_name'], unique=False, schema='app')
    op.create_index(op.f('ix_app_persons_full_name'), 'persons', ['full_name'], unique=False, schema='app')
    op.create_index(op.f('ix_app_persons_id'), 'persons', ['id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_persons_last_name'), 'persons', ['last_name'], unique=False, schema='app')
    op.create_index(op.f('ix_app_persons_masked_id'), 'persons', ['masked_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_persons_nationality_id'), 'persons', ['nationality_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_persons_passport_number'), 'persons', ['passport_number'], unique=False, schema='app')
    op.create_table('user_invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inviter_user_id', sa.UUID(), nullable=False),
    sa.Column('invited_email', sa.String(length=255), nullable=False),
    sa.Column('invited_month_key', sa.String(length=7), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_user_invites_invited_email'), 'user_invites', ['invited_email'], unique=False, schema='app')
    op.create_index(op.f('ix_app_user_invites_invited_month_key'), 'user_invites', ['invited_month_key'], unique=False, schema='app')
    op.create_index(op.f('ix_app_user_invites_inviter_user_id'), 'user_invites', ['inviter_user_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_user_invites_token'), 'user_invites', ['token'], unique=True, schema='app')
    op.create_table('announcements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trade_registry_name', sa.String(length=255), nullable=True),
    sa.Column('trade_registry_number', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('issue_number', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('announcement_type', sa.String(length=255), nullable=True),
    sa.Column('newspaper_name', sa.String(length=255), nullable=True),
    sa.Column('pdf_url', sa.String(length=1024), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['app.companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_announcements_id'), 'announcements', ['id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_announcements_publication_date'), 'announcements', ['publication_date'], unique=False, schema='app')
    op.create_index(op.f('ix_app_announcements_title'), 'announcements', ['title'], unique=False, schema='app')
    op.create_index(op.f('ix_app_announcements_trade_registry_name'), 'announcements', ['trade_registry_name'], unique=False, schema='app')
    op.create_index(op.f('ix_app_announcements_trade_registry_number'), 'announcements', ['trade_registry_number'], unique=False, schema='app')
    op.create_table('company_errors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['app.companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app.app_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_company_errors_id'), 'company_errors', ['id'], unique=False, schema='app')
    op.create_table('company_person_relations',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.Enum('BOARD_MEMBER', 'SHAREHOLDER', 'AUTHORIZED_SIGNATORY', 'AUDITOR', 'LIQUIDATOR', 'OTHER', name='relationtype'), nullable=False),
    sa.Column('position', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('share_percentage', sa.String(length=20), nullable=True),
    sa.Column('share_amount', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['app.companies.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['app.persons.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'person_id'),
    schema='app'
    )
    op.create_index('idx_relation_company_person', 'company_person_relations', ['company_id', 'person_id', 'relation_type'], unique=False, schema='app')
    op.create_index('idx_relation_dates', 'company_person_relations', ['start_date', 'end_date'], unique=False, schema='app')
    op.create_index(op.f('ix_app_company_person_relations_end_date'), 'company_person_relations', ['end_date'], unique=False, schema='app')
    op.create_index(op.f('ix_app_company_person_relations_is_current'), 'company_person_relations', ['is_current'], unique=False, schema='app')
    op.create_index(op.f('ix_app_company_person_relations_relation_type'), 'company_person_relations', ['relation_type'], unique=False, schema='app')
    op.create_index(op.f('ix_app_company_person_relations_start_date'), 'company_person_relations', ['start_date'], unique=False, schema='app')
    op.create_table('file_uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('upload_type', sa.Enum('GAZETTE_PDF', 'COMPANY_DATA', 'PERSON_DATA', 'OTHER', name='fileuploadtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='fileuploadstatus'), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processed_records', sa.Integer(), nullable=True),
    sa.Column('failed_records', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('file_metadata', sa.JSON(), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['app.app_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_file_uploads_id'), 'file_uploads', ['id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_file_uploads_status'), 'file_uploads', ['status'], unique=False, schema='app')
    op.create_index(op.f('ix_app_file_uploads_uploaded_by_id'), 'file_uploads', ['uploaded_by_id'], unique=False, schema='app')
    op.create_table('gazette_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gazette_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('entry_type', sa.String(length=100), nullable=True),
    sa.Column('entry_date', sa.DateTime(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('processed_text', sa.Text(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('has_errors', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['app.companies.id'], ),
    sa.ForeignKeyConstraint(['gazette_id'], ['app.gazettes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('idx_entry_type_date', 'gazette_entries', ['entry_type', 'entry_date'], unique=False, schema='app')
    op.create_index(op.f('ix_app_gazette_entries_company_id'), 'gazette_entries', ['company_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_gazette_entries_entry_date'), 'gazette_entries', ['entry_date'], unique=False, schema='app')
    op.create_index(op.f('ix_app_gazette_entries_gazette_id'), 'gazette_entries', ['gazette_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_gazette_entries_id'), 'gazette_entries', ['id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_gazette_entries_is_processed'), 'gazette_entries', ['is_processed'], unique=False, schema='app')
    op.create_table('job_histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.Enum('FILE_UPLOAD', 'OCR_PROCESSING', 'DATA_IMPORT', 'DATA_EXPORT', 'REPORT_GENERATION', 'SYSTEM_MAINTENANCE', 'OTHER', name='jobtype'), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('file_upload_id', sa.UUID(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_upload_id'], ['app.file_uploads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app.app_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('idx_job_dates', 'job_histories', ['started_at', 'completed_at'], unique=False, schema='app')
    op.create_index('idx_job_type_status', 'job_histories', ['job_type', 'status'], unique=False, schema='app')
    op.create_index(op.f('ix_app_job_histories_file_upload_id'), 'job_histories', ['file_upload_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_job_histories_id'), 'job_histories', ['id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_job_histories_job_name'), 'job_histories', ['job_name'], unique=False, schema='app')
    op.create_index(op.f('ix_app_job_histories_job_type'), 'job_histories', ['job_type'], unique=False, schema='app')
    op.create_index(op.f('ix_app_job_histories_started_at'), 'job_histories', ['started_at'], unique=False, schema='app')
    op.create_index(op.f('ix_app_job_histories_status'), 'job_histories', ['status'], unique=False, schema='app')
    op.create_index(op.f('ix_app_job_histories_user_id'), 'job_histories', ['user_id'], unique=False, schema='app')
    op.create_table('ocr_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('publication_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issue_number', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('pdf_page_count', sa.Integer(), nullable=True),
    sa.Column('sicil_office_header', sa.Text(), nullable=True),
    sa.Column('sicil_dosya_no', sa.Text(), nullable=True),
    sa.Column('mersis_no', sa.Text(), nullable=True),
    sa.Column('trade_name', sa.Text(), nullable=True),
    sa.Column('old_trade_name', sa.Text(), nullable=True),
    sa.Column('addresses', sa.JSON(), nullable=True),
    sa.Column('old_addresses', sa.JSON(), nullable=True),
    sa.Column('persons', sa.JSON(), nullable=True),
    sa.Column('masked_ids', sa.JSON(), nullable=True),
    sa.Column('hususlar', sa.JSON(), nullable=True),
    sa.Column('belgeler', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('item_index', sa.Integer(), nullable=True),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('is_derived', sa.Boolean(), nullable=True),
    sa.Column('derived_from_index', sa.Integer(), nullable=True),
    sa.Column('ilan_sira_no', sa.JSON(), nullable=True),
    sa.Column('content_sha256', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('markdown_content', sa.Text(), nullable=True),
    sa.Column('json_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['announcement_id'], ['app.announcements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['app.companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_ocr_results_announcement_id'), 'ocr_results', ['announcement_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_ocr_results_company_id'), 'ocr_results', ['company_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_ocr_results_id'), 'ocr_results', ['id'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_ocr_results_id'), table_name='ocr_results', schema='app')
    op.drop_index(op.f('ix_app_ocr_results_company_id'), table_name='ocr_results', schema='app')
    op.drop_index(op.f('ix_app_ocr_results_announcement_id'), table_name='ocr_results', schema='app')
    op.drop_table('ocr_results', schema='app')
    op.drop_index(op.f('ix_app_job_histories_user_id'), table_name='job_histories', schema='app')
    op.drop_index(op.f('ix_app_job_histories_status'), table_name='job_histories', schema='app')
    op.drop_index(op.f('ix_app_job_histories_started_at'), table_name='job_histories', schema='app')
    op.drop_index(op.f('ix_app_job_histories_job_type'), table_name='job_histories', schema='app')
    op.drop_index(op.f('ix_app_job_histories_job_name'), table_name='job_histories', schema='app')
    op.drop_index(op.f('ix_app_job_histories_id'), table_name='job_histories', schema='app')
    op.drop_index(op.f('ix_app_job_histories_file_upload_id'), table_name='job_histories', schema='app')
    op.drop_index('idx_job_type_status', table_name='job_histories', schema='app')
    op.drop_index('idx_job_dates', table_name='job_histories', schema='app')
    op.drop_table('job_histories', schema='app')
    op.drop_index(op.f('ix_app_gazette_entries_is_processed'), table_name='gazette_entries', schema='app')
    op.drop_index(op.f('ix_app_gazette_entries_id'), table_name='gazette_entries', schema='app')
    op.drop_index(op.f('ix_app_gazette_entries_gazette_id'), table_name='gazette_entries', schema='app')
    op.drop_index(op.f('ix_app_gazette_entries_entry_date'), table_name='gazette_entries', schema='app')
    op.drop_index(op.f('ix_app_gazette_entries_company_id'), table_name='gazette_entries', schema='app')
    op.drop_index('idx_entry_type_date', table_name='gazette_entries', schema='app')
    op.drop_table('gazette_entries', schema='app')
    op.drop_index(op.f('ix_app_file_uploads_uploaded_by_id'), table_name='file_uploads', schema='app')
    op.drop_index(op.f('ix_app_file_uploads_status'), table_name='file_uploads', schema='app')
    op.drop_index(op.f('ix_app_file_uploads_id'), table_name='file_uploads', schema='app')
    op.drop_table('file_uploads', schema='app')
    op.drop_index(op.f('ix_app_company_person_relations_start_date'), table_name='company_person_relations', schema='app')
    op.drop_index(op.f('ix_app_company_person_relations_relation_type'), table_name='company_person_relations', schema='app')
    op.drop_index(op.f('ix_app_company_person_relations_is_current'), table_name='company_person_relations', schema='app')
    op.drop_index(op.f('ix_app_company_person_relations_end_date'), table_name='company_person_relations', schema='app')
    op.drop_index('idx_relation_dates', table_name='company_person_relations', schema='app')
    op.drop_index('idx_relation_company_person', table_name='company_person_relations', schema='app')
    op.drop_table('company_person_relations', schema='app')
    op.drop_index(op.f('ix_app_company_errors_id'), table_name='company_errors', schema='app')
    op.drop_table('company_errors', schema='app')
    op.drop_index(op.f('ix_app_announcements_trade_registry_number'), table_name='announcements', schema='app')
    op.drop_index(op.f('ix_app_announcements_trade_registry_name'), table_name='announcements', schema='app')
    op.drop_index(op.f('ix_app_announcements_title'), table_name='announcements', schema='app')
    op.drop_index(op.f('ix_app_announcements_publication_date'), table_name='announcements', schema='app')
    op.drop_index(op.f('ix_app_announcements_id'), table_name='announcements', schema='app')
    op.drop_table('announcements', schema='app')
    op.drop_index(op.f('ix_app_user_invites_token'), table_name='user_invites', schema='app')
    op.drop_index(op.f('ix_app_user_invites_inviter_user_id'), table_name='user_invites', schema='app')
    op.drop_index(op.f('ix_app_user_invites_invited_month_key'), table_name='user_invites', schema='app')
    op.drop_index(op.f('ix_app_user_invites_invited_email'), table_name='user_invites', schema='app')
    op.drop_table('user_invites', schema='app')
    op.drop_index(op.f('ix_app_persons_passport_number'), table_name='persons', schema='app')
    op.drop_index(op.f('ix_app_persons_nationality_id'), table_name='persons', schema='app')
    op.drop_index(op.f('ix_app_persons_masked_id'), table_name='persons', schema='app')
    op.drop_index(op.f('ix_app_persons_last_name'), table_name='persons', schema='app')
    op.drop_index(op.f('ix_app_persons_id'), table_name='persons', schema='app')
    op.drop_index(op.f('ix_app_persons_full_name'), table_name='persons', schema='app')
    op.drop_index(op.f('ix_app_persons_first_name'), table_name='persons', schema='app')
    op.drop_index(op.f('ix_app_persons_email'), table_name='persons', schema='app')
    op.drop_index('idx_person_name_trgm', table_name='persons', schema='app', postgresql_using='gin', postgresql_ops={'full_name': 'gin_trgm_ops'})
    op.drop_table('persons', schema='app')
    op.drop_index(op.f('ix_app_incoming_emails_to_address'), table_name='incoming_emails', schema='app')
    op.drop_index(op.f('ix_app_incoming_emails_received_at'), table_name='incoming_emails', schema='app')
    op.drop_index(op.f('ix_app_incoming_emails_is_read'), table_name='incoming_emails', schema='app')
    op.drop_index(op.f('ix_app_incoming_emails_id'), table_name='incoming_emails', schema='app')
    op.drop_index(op.f('ix_app_incoming_emails_from_address'), table_name='incoming_emails', schema='app')
    op.drop_index(op.f('ix_app_incoming_emails_cloudflare_message_id'), table_name='incoming_emails', schema='app')
    op.drop_table('incoming_emails', schema='app')
    op.drop_index(op.f('ix_app_geocoding_cache_address_hash'), table_name='geocoding_cache', schema='app')
    op.drop_table('geocoding_cache', schema='app')
    op.drop_index(op.f('ix_app_gazettes_is_processed'), table_name='gazettes', schema='app')
    op.drop_index(op.f('ix_app_gazettes_id'), table_name='gazettes', schema='app')
    op.drop_index(op.f('ix_app_gazettes_gazette_number'), table_name='gazettes', schema='app')
    op.drop_index(op.f('ix_app_gazettes_gazette_date'), table_name='gazettes', schema='app')
    op.drop_index('idx_gazette_date_type', table_name='gazettes', schema='app')
    op.drop_table('gazettes', schema='app')
    op.drop_index(op.f('ix_app_daily_usages_user_id'), table_name='daily_usages', schema='app')
    op.drop_index(op.f('ix_app_daily_usages_day'), table_name='daily_usages', schema='app')
    op.drop_table('daily_usages', schema='app')
    op.drop_index(op.f('ix_app_contact_messages_id'), table_name='contact_messages', schema='app')
    op.drop_index(op.f('ix_app_contact_messages_email'), table_name='contact_messages', schema='app')
    op.drop_table('contact_messages', schema='app')
    op.drop_index(op.f('ix_app_companies_unvan_unaccent'), table_name='companies', schema='app')
    op.drop_index(op.f('ix_app_companies_unvan'), table_name='companies', schema='app')
    op.drop_index(op.f('ix_app_companies_sicil_office_code'), table_name='companies', schema='app')
    op.drop_index(op.f('ix_app_companies_sicil_no'), table_name='companies', schema='app')
    op.drop_index(op.f('ix_app_companies_mersis_number'), table_name='companies', schema='app')
    op.drop_index(op.f('ix_app_companies_id'), table_name='companies', schema='app')
    op.drop_table('companies', schema='app')
    op.drop_index(op.f('ix_app_app_users_id'), table_name='app_users', schema='app')
    op.drop_index(op.f('ix_app_app_users_email'), table_name='app_users', schema='app')
    op.drop_table('app_users', schema='app')
    op.drop_index(op.f('ix_app_app_settings_key'), table_name='app_settings', schema='app')
    op.drop_table('app_settings', schema='app')
    # ### end Alembic commands ###
