"""geocoding_cache

Revision ID: d5f442394ed6
Revises: c0ffee000001
Create Date: 2026-02-28 16:23:26.686703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd5f442394ed6'
down_revision = 'c0ffee000001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geocoding_cache',
    sa.Column('address_hash', sa.String(length=64), nullable=False),
    sa.Column('address_text', sa.String(length=1000), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('address_hash'),
    schema='app'
    )
    op.create_index(op.f('ix_app_geocoding_cache_address_hash'), 'geocoding_cache', ['address_hash'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_geocoding_cache_address_hash'), table_name='geocoding_cache', schema='app')
    op.drop_table('geocoding_cache', schema='app')
    # ### end Alembic commands ###
