FROM node:18-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

# 1. Next.js standalone çıktılarını kopyala (Sunucuda npm install yapmaya gerek bırakmaz)
COPY .next/standalone ./
COPY .next/static ./.next/static
COPY public ./public

# Environment
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

EXPOSE 3000
CMD ["node", "server.js"]

