"""Restore address and nace_code to Company model

Revision ID: 1ff3cf411698
Revises: 8cf22b64329c
Create Date: 2025-07-03 08:57:12.099070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ff3cf411698'
down_revision = '8cf22b64329c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('nace_code', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'address')
    op.drop_column('companies', 'nace_code')
    # ### end Alembic commands ###
