"""Final migration with correct data types

Revision ID: 56c269f47ffa
Revises: 
Create Date: 2025-07-01 21:34:41.620805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56c269f47ffa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trade_registry_name', sa.String(length=255), nullable=True),
    sa.Column('trade_registry_number', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('announcement_date', sa.DateTime(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('pdf_link', sa.String(length=1024), nullable=True),
    sa.Column('pdf_saved_to_supabase', sa.Boolean(), nullable=True),
    sa.Column('supabase_path', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_announcement_date'), 'announcements', ['announcement_date'], unique=False)
    op.create_index(op.f('ix_announcements_id'), 'announcements', ['id'], unique=False)
    op.create_index(op.f('ix_announcements_pdf_saved_to_supabase'), 'announcements', ['pdf_saved_to_supabase'], unique=False)
    op.create_index(op.f('ix_announcements_title'), 'announcements', ['title'], unique=False)
    op.create_index(op.f('ix_announcements_trade_registry_name'), 'announcements', ['trade_registry_name'], unique=False)
    op.create_index(op.f('ix_announcements_trade_registry_number'), 'announcements', ['trade_registry_number'], unique=False)
    op.create_table('app_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'USER', name='userrole'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_users_email'), 'app_users', ['email'], unique=True)
    op.create_index(op.f('ix_app_users_id'), 'app_users', ['id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), server_default='', nullable=False),
    sa.Column('trade_name', sa.String(length=500), nullable=True),
    sa.Column('tax_number', sa.String(length=50), nullable=True),
    sa.Column('mersis_number', sa.String(length=50), nullable=True),
    sa.Column('trade_registry_number', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('establishment_date', sa.DateTime(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_company_title_trgm', 'companies', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_mersis_number'), 'companies', ['mersis_number'], unique=True)
    op.create_index(op.f('ix_companies_tax_number'), 'companies', ['tax_number'], unique=True)
    op.create_index(op.f('ix_companies_title'), 'companies', ['title'], unique=False)
    op.create_index(op.f('ix_companies_trade_registry_number'), 'companies', ['trade_registry_number'], unique=False)
    op.create_table('company_scrapes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sicil_no', sa.String(), nullable=False),
    sa.Column('firma_unvani', sa.String(), nullable=True),
    sa.Column('is_scraped', sa.Boolean(), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_scrapes_id'), 'company_scrapes', ['id'], unique=False)
    op.create_index(op.f('ix_company_scrapes_sicil_no'), 'company_scrapes', ['sicil_no'], unique=True)
    op.create_table('gazettes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gazette_number', sa.String(length=100), nullable=True),
    sa.Column('gazette_date', sa.DateTime(), nullable=False),
    sa.Column('gazette_type', sa.Enum('TRADE', 'ANNOUNCEMENT', 'OTHER', name='gazettetype'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gazette_date_type', 'gazettes', ['gazette_date', 'gazette_type'], unique=False)
    op.create_index(op.f('ix_gazettes_gazette_date'), 'gazettes', ['gazette_date'], unique=False)
    op.create_index(op.f('ix_gazettes_gazette_number'), 'gazettes', ['gazette_number'], unique=False)
    op.create_index(op.f('ix_gazettes_id'), 'gazettes', ['id'], unique=False)
    op.create_index(op.f('ix_gazettes_is_processed'), 'gazettes', ['is_processed'], unique=False)
    op.create_table('persons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=300), nullable=True),
    sa.Column('nationality_id', sa.String(length=20), nullable=True),
    sa.Column('passport_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('birth_place', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_person_name_trgm', 'persons', ['full_name'], unique=False, postgresql_using='gin', postgresql_ops={'full_name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_persons_email'), 'persons', ['email'], unique=False)
    op.create_index(op.f('ix_persons_first_name'), 'persons', ['first_name'], unique=False)
    op.create_index(op.f('ix_persons_full_name'), 'persons', ['full_name'], unique=False)
    op.create_index(op.f('ix_persons_id'), 'persons', ['id'], unique=False)
    op.create_index(op.f('ix_persons_last_name'), 'persons', ['last_name'], unique=False)
    op.create_index(op.f('ix_persons_nationality_id'), 'persons', ['nationality_id'], unique=True)
    op.create_index(op.f('ix_persons_passport_number'), 'persons', ['passport_number'], unique=False)
    op.create_table('company_person_relations',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.Enum('BOARD_MEMBER', 'SHAREHOLDER', 'AUTHORIZED_SIGNATORY', 'AUDITOR', 'LIQUIDATOR', 'OTHER', name='relationtype'), nullable=False),
    sa.Column('position', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('share_percentage', sa.String(length=20), nullable=True),
    sa.Column('share_amount', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'person_id')
    )
    op.create_index('idx_relation_company_person', 'company_person_relations', ['company_id', 'person_id', 'relation_type'], unique=False)
    op.create_index('idx_relation_dates', 'company_person_relations', ['start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_company_person_relations_end_date'), 'company_person_relations', ['end_date'], unique=False)
    op.create_index(op.f('ix_company_person_relations_is_current'), 'company_person_relations', ['is_current'], unique=False)
    op.create_index(op.f('ix_company_person_relations_relation_type'), 'company_person_relations', ['relation_type'], unique=False)
    op.create_index(op.f('ix_company_person_relations_start_date'), 'company_person_relations', ['start_date'], unique=False)
    op.create_table('file_uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('upload_type', sa.Enum('GAZETTE_PDF', 'COMPANY_DATA', 'PERSON_DATA', 'OTHER', name='fileuploadtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='fileuploadstatus'), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processed_records', sa.Integer(), nullable=True),
    sa.Column('failed_records', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('file_metadata', sa.JSON(), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_uploads_id'), 'file_uploads', ['id'], unique=False)
    op.create_index(op.f('ix_file_uploads_status'), 'file_uploads', ['status'], unique=False)
    op.create_index(op.f('ix_file_uploads_uploaded_by_id'), 'file_uploads', ['uploaded_by_id'], unique=False)
    op.create_table('gazette_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gazette_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('entry_type', sa.String(length=100), nullable=True),
    sa.Column('entry_date', sa.DateTime(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('processed_text', sa.Text(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('has_errors', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['gazette_id'], ['gazettes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entry_type_date', 'gazette_entries', ['entry_type', 'entry_date'], unique=False)
    op.create_index(op.f('ix_gazette_entries_company_id'), 'gazette_entries', ['company_id'], unique=False)
    op.create_index(op.f('ix_gazette_entries_entry_date'), 'gazette_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_gazette_entries_gazette_id'), 'gazette_entries', ['gazette_id'], unique=False)
    op.create_index(op.f('ix_gazette_entries_id'), 'gazette_entries', ['id'], unique=False)
    op.create_index(op.f('ix_gazette_entries_is_processed'), 'gazette_entries', ['is_processed'], unique=False)
    op.create_table('job_histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.Enum('FILE_UPLOAD', 'OCR_PROCESSING', 'DATA_IMPORT', 'DATA_EXPORT', 'REPORT_GENERATION', 'SYSTEM_MAINTENANCE', 'OTHER', name='jobtype'), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('file_upload_id', sa.UUID(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_upload_id'], ['file_uploads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_dates', 'job_histories', ['started_at', 'completed_at'], unique=False)
    op.create_index('idx_job_type_status', 'job_histories', ['job_type', 'status'], unique=False)
    op.create_index(op.f('ix_job_histories_file_upload_id'), 'job_histories', ['file_upload_id'], unique=False)
    op.create_index(op.f('ix_job_histories_id'), 'job_histories', ['id'], unique=False)
    op.create_index(op.f('ix_job_histories_job_name'), 'job_histories', ['job_name'], unique=False)
    op.create_index(op.f('ix_job_histories_job_type'), 'job_histories', ['job_type'], unique=False)
    op.create_index(op.f('ix_job_histories_started_at'), 'job_histories', ['started_at'], unique=False)
    op.create_index(op.f('ix_job_histories_status'), 'job_histories', ['status'], unique=False)
    op.create_index(op.f('ix_job_histories_user_id'), 'job_histories', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_histories_user_id'), table_name='job_histories')
    op.drop_index(op.f('ix_job_histories_status'), table_name='job_histories')
    op.drop_index(op.f('ix_job_histories_started_at'), table_name='job_histories')
    op.drop_index(op.f('ix_job_histories_job_type'), table_name='job_histories')
    op.drop_index(op.f('ix_job_histories_job_name'), table_name='job_histories')
    op.drop_index(op.f('ix_job_histories_id'), table_name='job_histories')
    op.drop_index(op.f('ix_job_histories_file_upload_id'), table_name='job_histories')
    op.drop_index('idx_job_type_status', table_name='job_histories')
    op.drop_index('idx_job_dates', table_name='job_histories')
    op.drop_table('job_histories')
    op.drop_index(op.f('ix_gazette_entries_is_processed'), table_name='gazette_entries')
    op.drop_index(op.f('ix_gazette_entries_id'), table_name='gazette_entries')
    op.drop_index(op.f('ix_gazette_entries_gazette_id'), table_name='gazette_entries')
    op.drop_index(op.f('ix_gazette_entries_entry_date'), table_name='gazette_entries')
    op.drop_index(op.f('ix_gazette_entries_company_id'), table_name='gazette_entries')
    op.drop_index('idx_entry_type_date', table_name='gazette_entries')
    op.drop_table('gazette_entries')
    op.drop_index(op.f('ix_file_uploads_uploaded_by_id'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_uploads_status'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_uploads_id'), table_name='file_uploads')
    op.drop_table('file_uploads')
    op.drop_index(op.f('ix_company_person_relations_start_date'), table_name='company_person_relations')
    op.drop_index(op.f('ix_company_person_relations_relation_type'), table_name='company_person_relations')
    op.drop_index(op.f('ix_company_person_relations_is_current'), table_name='company_person_relations')
    op.drop_index(op.f('ix_company_person_relations_end_date'), table_name='company_person_relations')
    op.drop_index('idx_relation_dates', table_name='company_person_relations')
    op.drop_index('idx_relation_company_person', table_name='company_person_relations')
    op.drop_table('company_person_relations')
    op.drop_index(op.f('ix_persons_passport_number'), table_name='persons')
    op.drop_index(op.f('ix_persons_nationality_id'), table_name='persons')
    op.drop_index(op.f('ix_persons_last_name'), table_name='persons')
    op.drop_index(op.f('ix_persons_id'), table_name='persons')
    op.drop_index(op.f('ix_persons_full_name'), table_name='persons')
    op.drop_index(op.f('ix_persons_first_name'), table_name='persons')
    op.drop_index(op.f('ix_persons_email'), table_name='persons')
    op.drop_index('idx_person_name_trgm', table_name='persons', postgresql_using='gin', postgresql_ops={'full_name': 'gin_trgm_ops'})
    op.drop_table('persons')
    op.drop_index(op.f('ix_gazettes_is_processed'), table_name='gazettes')
    op.drop_index(op.f('ix_gazettes_id'), table_name='gazettes')
    op.drop_index(op.f('ix_gazettes_gazette_number'), table_name='gazettes')
    op.drop_index(op.f('ix_gazettes_gazette_date'), table_name='gazettes')
    op.drop_index('idx_gazette_date_type', table_name='gazettes')
    op.drop_table('gazettes')
    op.drop_index(op.f('ix_company_scrapes_sicil_no'), table_name='company_scrapes')
    op.drop_index(op.f('ix_company_scrapes_id'), table_name='company_scrapes')
    op.drop_table('company_scrapes')
    op.drop_index(op.f('ix_companies_trade_registry_number'), table_name='companies')
    op.drop_index(op.f('ix_companies_title'), table_name='companies')
    op.drop_index(op.f('ix_companies_tax_number'), table_name='companies')
    op.drop_index(op.f('ix_companies_mersis_number'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index('idx_company_title_trgm', table_name='companies', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_table('companies')
    op.drop_index(op.f('ix_app_users_id'), table_name='app_users')
    op.drop_index(op.f('ix_app_users_email'), table_name='app_users')
    op.drop_table('app_users')
    op.drop_index(op.f('ix_announcements_trade_registry_number'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_trade_registry_name'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_title'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_pdf_saved_to_supabase'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_id'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_announcement_date'), table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###
