"""Add sicil_mudurluk to companies table

Revision ID: 94332f5bfb7f
Revises: 56c269f47ffa
Create Date: 2025-07-01 22:23:32.973382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94332f5bfb7f'
down_revision = '56c269f47ffa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('sicil_mudurluk', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'sicil_mudurluk')
    # ### end Alembic commands ###
