"""Add unique constraint to trade_registry_number

Revision ID: c78e9c7e2a6e
Revises: 94332f5bfb7f
Create Date: 2025-07-01 22:26:53.813271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c78e9c7e2a6e'
down_revision = '94332f5bfb7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_companies_trade_registry_number', table_name='companies')
    op.create_index(op.f('ix_companies_trade_registry_number'), 'companies', ['trade_registry_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_trade_registry_number'), table_name='companies')
    op.create_index('ix_companies_trade_registry_number', 'companies', ['trade_registry_number'], unique=False)
    # ### end Alembic commands ###
